
export const EVENTS = {
  TEST: 'TEST',
  DISCONNECT: 'disconnect',
  SEND_MESSAGE: 'SEND_MESSAGE',
  BROADCAST_MESSAGE: 'BROADCAST_MESSAGE',
  SEND_USERNAME: 'SEND_USERNAME',
  BROADCAST_RECENT_USERS: 'BROADCAST_RECENT_USERS'
};
