
export const EVENTS = {
  TEST: 'TEST',
  SEND_MESSAGE: 'SEND_MESSAGE',
  BROADCAST_MESSSAGE: 'BROADCAST_MESSSAGE',
  BROADCAST_USERS: 'BROADCAST_USERS',
  BROADCAST_USERS_LIST: 'BROADCAST_USERS_LIST',
  DISCONNECT: 'disconnect'
};
